// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu5XLu06OqLoUX6bDDe08bNcRRyFW6pE0',
    appId: '1:11267986529:web:43d8d08350324cd8660620',
    messagingSenderId: '11267986529',
    projectId: 'peak-pulse-94172',
    authDomain: 'peak-pulse-94172.firebaseapp.com',
    storageBucket: 'peak-pulse-94172.appspot.com',
    measurementId: 'G-XQYRDR0J2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAujYXEAxxZHpSDyW-84eN9-FfsuYSzEqU',
    appId: '1:11267986529:android:3460900d4c8824ea660620',
    messagingSenderId: '11267986529',
    projectId: 'peak-pulse-94172',
    storageBucket: 'peak-pulse-94172.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb_g1s3Czd7Y-Imqu8eWEct0t8n42QcBY',
    appId: '1:11267986529:ios:2bd029099f2e7d4d660620',
    messagingSenderId: '11267986529',
    projectId: 'peak-pulse-94172',
    storageBucket: 'peak-pulse-94172.appspot.com',
    iosBundleId: 'com.example.peakpulseTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb_g1s3Czd7Y-Imqu8eWEct0t8n42QcBY',
    appId: '1:11267986529:ios:2bd029099f2e7d4d660620',
    messagingSenderId: '11267986529',
    projectId: 'peak-pulse-94172',
    storageBucket: 'peak-pulse-94172.appspot.com',
    iosBundleId: 'com.example.peakpulseTest1',
  );
}
